sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.2'
before_install:
  - npm i -g npm@^3.10.3
  - sudo apt-get install libgnome-keyring-dev
before_script:
  - npm prune
script:
  - npm run build
  - npm run test:single
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
