sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.2'
sudo: true
before_install:
  - npm i -g npm@^3.10.3
  - sudo apt-get install libgnome-keyring-dev
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
